# Generated by Django 4.0.2 on 2022-03-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='owner',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='scoreOfRecipe',
            field=models.FloatField(default=None, null=True),
        ),
    ]
